"""added columns to template table

Revision ID: 0e44da18a326
Revises: afd1c41bc7e3
Create Date: 2024-11-09 15:02:02.442178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44da18a326'
down_revision = 'afd1c41bc7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_template', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('template_redflag', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.drop_column('template_redflag')
        batch_op.drop_column('sender_template')

    # ### end Alembic commands ###
