"""Initial migration

Revision ID: 12a5e15dcaa0
Revises: 
Create Date: 2024-10-25 21:27:55.638144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a5e15dcaa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interaction', schema=None) as batch_op:
        batch_op.drop_column('reported')

    # ### end Alembic commands ###
