"""added a redflag column to phishing_email table

Revision ID: 51352265986f
Revises: 0e44da18a326
Create Date: 2024-11-11 16:50:47.570672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51352265986f'
down_revision = '0e44da18a326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_flag', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.drop_column('red_flag')

    # ### end Alembic commands ###
