"""initial migration

Revision ID: 562760b498f4
Revises: 
Create Date: 2024-10-19 12:33:30.177984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '562760b498f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=False))
        batch_op.add_column(sa.Column('sender', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('recipient', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_phishing_templates_tags'), ['tags'], unique=False)
        batch_op.drop_column('diffculty_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diffculty_level', mysql.ENUM('beginner', 'intermediate', 'advanced'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_phishing_templates_tags'))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('link')
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
