"""Apply detected schema changes

Revision ID: 650a9d572c55
Revises: a437078238e0
Create Date: 2024-11-03 22:21:11.321430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '650a9d572c55'
down_revision = 'a437078238e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questionnaire_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('response_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'questionnaire', ['questionnaire_id'], ['id'])
        batch_op.drop_column('question_id')
        batch_op.drop_column('boolean_response')
        batch_op.drop_column('response_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_text', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('boolean_response', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('response_ibfk_1', 'question', ['question_id'], ['id'])
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('questionnaire_id')

    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('answers')
    # ### end Alembic commands ###
