"""recreate migrations

Revision ID: a437078238e0
Revises: 
Create Date: 2024-10-29 22:32:37.858847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a437078238e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_template', sa.String(length=120), nullable=False))
        batch_op.drop_column('subject_temlpate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_temlpate', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('subject_template')

    # ### end Alembic commands ###
