"""Initial migration

Revision ID: b2b66c4578e5
Revises: 
Create Date: 2024-11-29 20:48:48.644283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b66c4578e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.drop_column('instructor_feedback')

    # ### end Alembic commands ###
