"""added foreign key to phishing emails for associated peer phishing template

Revision ID: c824cdca3e7e
Revises: 4bed06b83fe9
Create Date: 2024-12-05 17:25:11.966272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c824cdca3e7e'
down_revision = '4bed06b83fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_phishing_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'peer_phishing_templates', ['peer_phishing_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('peer_phishing_template_id')

    # ### end Alembic commands ###
