"""added student profiles table and student profile tags to attach tags to students based on answers

Revision ID: c969bc2b1bc5
Revises: af640fa3690c
Create Date: 2024-11-18 13:58:35.162984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c969bc2b1bc5'
down_revision = 'af640fa3690c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('email_used_for_platforms', sa.String(length=120), nullable=False),
    sa.Column('employement_status', sa.String(length=120), nullable=False),
    sa.Column('employer', sa.String(length=120), nullable=True),
    sa.Column('risk_level', sa.String(length=120), nullable=False),
    sa.Column('attention_to_detail', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profile_tags',
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('student_profile_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profile_tags')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
