"""Initial migration

Revision ID: d0dc2e457a7c
Revises: 
Create Date: 2024-10-19 12:19:10.206331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0dc2e457a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userProfile', schema=None) as batch_op:
        batch_op.drop_index('student_id')

    op.drop_table('userProfile')
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=False))
        batch_op.add_column(sa.Column('sender', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('recipient', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_phishing_templates_tags'), ['tags'], unique=False)
        batch_op.drop_column('diffculty_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diffculty_level', mysql.ENUM('beginner', 'intermediate', 'advanced'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_phishing_templates_tags'))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('link')
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('tags')

    op.create_table('userProfile',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('major', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('courses', mysql.TEXT(), nullable=False),
    sa.Column('prefered_device', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('prefered_social_media', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('use_2fa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='userProfile_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('userProfile', schema=None) as batch_op:
        batch_op.create_index('student_id', ['student_id'], unique=True)

    # ### end Alembic commands ###
