"""added models to track peer phishing templates and their associated tags

Revision ID: f3336ef53c0f
Revises: b2b66c4578e5
Create Date: 2024-12-05 15:50:38.059645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3336ef53c0f'
down_revision = 'b2b66c4578e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_phishing_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='difficultylevel'), nullable=False),
    sa.Column('sender_template', sa.String(length=120), nullable=False),
    sa.Column('subject_template', sa.String(length=120), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('template_redflag', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peer_phishing_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_phishing_templates_name'), ['name'], unique=True)

    op.create_table('peer_phishing_template_tags',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['peer_phishing_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peer_phishing_template_tags')
    with op.batch_alter_table('peer_phishing_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_phishing_templates_name'))

    op.drop_table('peer_phishing_templates')
    # ### end Alembic commands ###
